/*
**	Main Events Loop
**	Automatically generated by Emperor
*/

#include "includes.h"

void Events( void )
{
	ULONG	wait,
			app = (1L << AppPort->mp_SigBit);

	ULONG	done = FALSE;

	ULONG	result;

	UWORD	code;
	while(!done)
	{
		wait = IExec->Wait( SIGBREAKF_CTRL_C | app );
		if ( wait & SIGBREAKF_CTRL_C )
		{
			done = TRUE;
		}
    	else
		{
			while((result = RA_HandleInput(obj[OID_WindowObject1], &code)) != WMHI_LASTMSG)
			{
				switch(result & WMHI_CLASSMASK)
				{
					case WMHI_GADGETUP:
						switch(result & WMHI_GADGETMASK)
						{
							case GID_Button1: Button1_GadgetUp_Evt(); break;
							case GID_Button2: Button2_GadgetUp_Evt(); break; 
							case GID_Button5: Button5_GadgetUp_Evt(); break;
							case GID_Button6: Button6_GadgetUp_Evt(); break;
							case GID_Button7: Button7_GadgetUp_Evt(); break;
							case GID_Button8: Button8_GadgetUp_Evt(); break;     
							case GID_String1: Button2_GadgetUp_Evt(); break;
							default: break;
						}
						break;
					case WMHI_MENUPICK:
						switch(result & WMHI_MENUMASK)
						{
							case Menu_Information1: Menu_Information1_MenuPick_Evt(); break;
							case Menu_prefs: Menu_prefs_MenuPick_Evt(); break;
							case Menu_Quit1: Menu_Quit1_MenuPick_Evt(); break;
							case Menuitem1: Menuitem1_MenuPick_Evt(); break;
							case Menuitem2: Menuitem2_MenuPick_Evt(); break;
							case Menuitem3: Menuitem3_MenuPick_Evt(); break;
							case Menuitem4: Menuitem4_MenuPick_Evt(); break;
							case Menuitem5: Menuitem5_MenuPick_Evt(); break;
							case Menuitem6: Menuitem6_MenuPick_Evt(); break;
							default: break;
						}
						break;
					case WMHI_MENUHELP:
						switch(result & WMHI_MENUMASK)
						{
							default: break;
						}
						break;
					case WMHI_CLOSEWINDOW:
						Window1_CloseWindow_Evt();
						break;
					case WMHI_ICONIFY:
						Window1_IconifyWindow_Evt();
						break;
					case WMHI_UNICONIFY:
						Window1_UnIconifyWindow_Evt();
						break;
					case WMHI_ACTIVE:
						break;
					case WMHI_INACTIVE:
						break;
					case WMHI_RAWKEY:
						break;
					case WMHI_VANILLAKEY:
						break;
					case WMHI_MOUSEBUTTONS:
						break;
					case WMHI_MOUSEMOVE:
						break;
					case WMHI_NEWSIZE:
						break;
					case WMHI_CHANGEWINDOW:
						break;
					case WMHI_DISPOSEDWINDOW:
						break;
					case WMHI_INTUITICK:
						break;
				}
			}
			while((result = RA_HandleInput(obj[OID_WindowObject2], &code)) != WMHI_LASTMSG)
			{
				switch(result & WMHI_CLASSMASK)
				{
					case WMHI_GADGETUP:
						switch(result & WMHI_GADGETMASK)
						{                                    							 
							case GID_Button3: Button3_GadgetUp_Evt(); break;
							case GID_Button4: Window2_CloseWindow_Evt(); break;
							default: break;
						}
						break;
					case WMHI_MENUPICK:
						switch(result & WMHI_MENUMASK)
						{
							
							default: break;
						}
						break;
					case WMHI_MENUHELP:
						switch(result & WMHI_MENUMASK)
						{
							default: break;
						}
						break;
					case WMHI_CLOSEWINDOW:
						Window2_CloseWindow_Evt();
						break;
					case WMHI_ICONIFY:
						break;
					case WMHI_UNICONIFY:
						break;
					case WMHI_ACTIVE:
						break;
					case WMHI_INACTIVE:
						break;
					case WMHI_RAWKEY:
						break;
					case WMHI_VANILLAKEY:
						break;
					case WMHI_MOUSEBUTTONS:
						break;
					case WMHI_MOUSEMOVE:
						break;
					case WMHI_NEWSIZE:
						break;
					case WMHI_CHANGEWINDOW:
						break;
					case WMHI_DISPOSEDWINDOW:
						break;
					case WMHI_INTUITICK:
						break;
				}
			}
			while((result = RA_HandleInput(obj[OID_WindowObject3], &code)) != WMHI_LASTMSG)
			{
				switch(result & WMHI_CLASSMASK)
				{
					case WMHI_GADGETUP:
						switch(result & WMHI_GADGETMASK)
						{
							case GID_Button9: Button9_GadgetUp_Evt(); break;
							case GID_Button10: Button10_GadgetUp_Evt(); break;
							case GID_Button11: Button11_GadgetUp_Evt(); break;
							case GID_Listbrowser1: Listbrowser1_GadgetUp_Evt(); break;
							default: break;
						}
						break;
					case WMHI_MENUPICK:
						switch(result & WMHI_MENUMASK)
						{
							case Menu_prefs: Menu_prefs_MenuPick_Evt(); break;
							default: break;
						}
						break;
					case WMHI_MENUHELP:
						switch(result & WMHI_MENUMASK)
						{
							default: break;
						}
						break;
					case WMHI_CLOSEWINDOW:
						break;
					case WMHI_ICONIFY:
						break;
					case WMHI_UNICONIFY:
						break;
					case WMHI_ACTIVE:
						break;
					case WMHI_INACTIVE:
						break;
					case WMHI_RAWKEY:
						break;
					case WMHI_VANILLAKEY:
						break;
					case WMHI_MOUSEBUTTONS:
						break;
					case WMHI_MOUSEMOVE:
						break;
					case WMHI_NEWSIZE:
						break;
					case WMHI_CHANGEWINDOW:
						break;
					case WMHI_DISPOSEDWINDOW:
						break;
					case WMHI_INTUITICK:
						break;
				}
			}
			while((result = RA_HandleInput(obj[OID_WindowObject4], &code)) != WMHI_LASTMSG)
			{
				switch(result & WMHI_CLASSMASK)
				{
					case WMHI_GADGETUP:
						switch(result & WMHI_GADGETMASK)
						{
							case GID_String_4_1: Button_4_1_GadgetUp_Evt(); break;
							case GID_Button_4_1: Button_4_1_GadgetUp_Evt(); break;
							default: break;
						}
						break;
					case WMHI_MENUPICK:
						switch(result & WMHI_MENUMASK)
						{
							case Menu_prefs: Menu_prefs_MenuPick_Evt(); break;
							default: break;
						}
						break;
					case WMHI_MENUHELP:
						switch(result & WMHI_MENUMASK)
						{
							default: break;
						}
						break;
					case WMHI_CLOSEWINDOW:
						Window4_CloseWindow_Evt();
						break;
					case WMHI_ICONIFY:
						break;
					case WMHI_UNICONIFY:
						break;
					case WMHI_ACTIVE:
						break;
					case WMHI_INACTIVE:
						break;
					case WMHI_RAWKEY:
						break;
					case WMHI_VANILLAKEY:
						break;
					case WMHI_MOUSEBUTTONS:
						break;
					case WMHI_MOUSEMOVE:
						break;
					case WMHI_NEWSIZE:
						break;
					case WMHI_CHANGEWINDOW:
						break;
					case WMHI_DISPOSEDWINDOW:
						break;
					case WMHI_INTUITICK:
						break;
				}
			}

		}
	}
}
