/*
**	system Structures stuff
**	Automatically generated by Emperor
*/


struct NewMenu Menu[] =
{
	{ NM_TITLE, 0, 0, 0, 0, 0 },
	{ NM_ITEM, 0, "I", 0, 0, 0 },
	{ NM_ITEM, 0, "P", 0, 0, 0 },
	{ NM_ITEM, NM_BARLABEL, 0, 0, 0, 0 },
	{ NM_ITEM, 0, "Q", 0, 0, 0 },
	{ NM_TITLE, 0, 0, 0, 0, 0 },
	{ NM_ITEM, 0, 0, 0, 0, 0 },
	{ NM_ITEM, 0, 0, 0, 0, 0 },
	{ NM_ITEM, 0, 0, 0, 0, 0 },
	{ NM_ITEM, 0, 0, 0, 0, 0 },
	{ NM_ITEM, 0, 0, 0, 0, 0 },
	{ NM_ITEM, 0, 0, 0, 0, 0 },
	{ NM_END, 0, 0, 0, 0, 0 }
};

struct TagItem Ep_ModeIDtags_Screen1[] =
{
	{BIDTAG_Depth, 0},
	{BIDTAG_NominalWidth, 0},
	{BIDTAG_NominalHeight, 0},
};
struct HintInfo	Hint_WindowObject1[]=
{
	{-1,-1,NULL,0L}
};

struct HintInfo	Hint_WindowObject2[]=
{
	{-1,-1,NULL,0L}
};

