/*
**	Graphical objects creation 
**	Automatically generated by Emperor
*/

#include "includes.h"
#include "gui.h"

void InitStuff()
{

	Menu[0].nm_Label = "Project";
	Menu[1].nm_Label = "Information";
	Menu[2].nm_Label = "Preferences";
	Menu[3].nm_Label = NM_BARLABEL;
	Menu[4].nm_Label = "Quit";
	Menu[5].nm_Label = "Bookmarks";
	Menu[6].nm_Label = "Amigaworld.net";
	Menu[7].nm_Label = "Amiga-news.de";
	Menu[8].nm_Label = "OS4Depot";
	Menu[9].nm_Label = "Amigans";
	Menu[10].nm_Label = "AmigaHellas.gr";
    Menu[11].nm_Label = "Utilitybase.com";

	Hint_WindowObject1[0].hi_Text = NULL;

	Hint_WindowObject2[0].hi_Text = NULL;

}

void InitWindows()
{
    struct Image *img_back=NULL, *img_forw=NULL, *img_home=NULL, *img_stop=NULL, *img_go=NULL, *img_google=NULL;
	struct Image *img_addr=NULL, *img_addradd=NULL, *img_addrdel=NULL, *img_edit=NULL;
    struct BitMap *bitmap;

    img_back=BitMapObject,
		BITMAP_SourceFile, "TBImages:nav_west",
        BITMAP_Screen, Screen1,
        BITMAP_Precision, PRECISION_EXACT,
        BITMAP_Transparent, TRUE,
        BITMAP_Masking, TRUE,
        BitMapEnd;

    img_forw=BitMapObject,
		BITMAP_SourceFile, "TBImages:nav_east",
        BITMAP_Screen, Screen1,
        BITMAP_Precision, PRECISION_EXACT,
        BITMAP_Transparent, TRUE,
        BITMAP_Masking, TRUE,
        BitMapEnd;

    img_home=BitMapObject,
		BITMAP_SourceFile, "TBImages:home",
        BITMAP_Screen, Screen1,
        BITMAP_Precision, PRECISION_EXACT,
        BITMAP_Transparent, TRUE,
        BITMAP_Masking, TRUE,
        BitMapEnd;

    img_go=BitMapObject,
		BITMAP_SourceFile, "TBImages:go",
        BITMAP_Screen, Screen1,
        BITMAP_Precision, PRECISION_EXACT,
        BITMAP_Transparent, TRUE,
        BITMAP_Masking, TRUE,
        BitMapEnd;

    img_google=BitMapObject,
		BITMAP_SourceFile, "TBImages:linkgoogle",
        BITMAP_Screen, Screen1,
        BITMAP_Precision, PRECISION_EXACT,
        BITMAP_Transparent, TRUE,
        BITMAP_Masking, TRUE,
        BitMapEnd;        

    img_stop=BitMapObject,
		BITMAP_SourceFile, "TBImages:stopall",
        BITMAP_Screen, Screen1,
        BITMAP_Precision, PRECISION_EXACT,
        BITMAP_Transparent, TRUE,
        BITMAP_Masking, TRUE,
        BitMapEnd;    

    img_addr=BitMapObject,
		BITMAP_SourceFile, "TBImages:addressbook",
        BITMAP_Screen, Screen1,
        BITMAP_Precision, PRECISION_EXACT,
        BITMAP_Transparent, TRUE,
        BITMAP_Masking, TRUE,
        BitMapEnd;

    img_addradd=BitMapObject,
		BITMAP_SourceFile, "TBImages:addressbookadd",
        BITMAP_Screen, Screen1,
        BITMAP_Precision, PRECISION_EXACT,
        BITMAP_Transparent, TRUE,
        BITMAP_Masking, TRUE,
        BitMapEnd;

    img_addrdel=BitMapObject,
		BITMAP_SourceFile, "TBImages:addressbookremove",
        BITMAP_Screen, Screen1,
        BITMAP_Precision, PRECISION_EXACT,
        BITMAP_Transparent, TRUE,
        BITMAP_Masking, TRUE,
        BitMapEnd;

	img_edit=BitMapObject,
		BITMAP_SourceFile, "TBImages:edit",
        BITMAP_Screen, Screen1,
        BITMAP_Precision, PRECISION_EXACT,
        BITMAP_Transparent, TRUE,
        BITMAP_Masking, TRUE,
        BitMapEnd;

	obj[OID_WindowObject1] = WindowObject,
		WA_Left, 0,
		WA_Top, 20,
		WA_Width, Screen1->Width,
		WA_Height, 40,
		WA_SizeGadget, FALSE,
		WA_DragBar, TRUE,
		WA_DepthGadget, TRUE,
		WA_CloseGadget, TRUE,
		WA_Activate, TRUE,
		WA_AutoAdjust, TRUE,
		WA_Title, "OWB_GUI",
		WA_ScreenTitle, PROGNAME " " VERSION"."REVISION " - "DATE" ©"DEVELOPER,
		WA_PubScreen, Screen1,
		WINDOW_GadgetHelp, TRUE,
		WINDOW_IconifyGadget, TRUE,
	    WINDOW_Icon, IIcon->GetDiskObject("PROGDIR:OWB_gui"),
		WINDOW_IconTitle, "OWB_GUI",
		WINDOW_AppPort, AppPort,
		WINDOW_SharedPort, AppPort,
		WINDOW_HintInfo,Hint_WindowObject1,
		WINDOW_NewMenu, Menu,
		WINDOW_ParentGroup, VGroupObject,
			LAYOUT_SpaceOuter, TRUE,
			LAYOUT_DeferLayout, TRUE,
			LAYOUT_AddChild,  gad[GID_Layout1] = LayoutObject,
				GA_ID, GID_Layout1,
				GA_RelVerify, TRUE,
				GA_GadgetHelp, TRUE,
				GA_UserData, 12,
				LAYOUT_Label, "",
				LAYOUT_Orientation, 0,
				LAYOUT_HorizAlignment, LALIGN_LEFT,
				LAYOUT_VertAlignment, LALIGN_CENTER,
				LAYOUT_LabelPlace, BVJ_TOP_CENTER,
				LAYOUT_BevelState, IDS_NORMAL,
				LAYOUT_BevelStyle, 4,
				LAYOUT_FixedHoriz, TRUE,
				LAYOUT_FixedVert, FALSE,

                LAYOUT_AddChild, gad[GID_Button6] = ButtonObject,
                    GA_ID, GID_Button6,
                    GA_Image, img_back,
                    ButtonEnd,
                CHILD_MaxWidth, 40,
                LAYOUT_AddChild, gad[GID_Button7] = ButtonObject,
                    GA_ID, GID_Button7,
                    GA_Image, img_forw,
                    ButtonEnd,
                CHILD_MaxWidth, 40,
                LAYOUT_AddChild, gad[GID_Button1] = ButtonObject,
                    GA_ID, GID_Button1,
                    GA_Image, img_home,
                    ButtonEnd,
                CHILD_MaxWidth, 40,
                LAYOUT_AddChild, gad[GID_Button8] = ButtonObject,
                    GA_ID, GID_Button8,
                    GA_Image, img_stop,
                    ButtonEnd,
                CHILD_MaxWidth, 40,
				LAYOUT_AddChild, gad[GID_String1] = StringObject,
					GA_ID, GID_String1,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_TabCycle, TRUE,
					STRINGA_TextVal, "",
					STRINGA_MaxChars, 200,
					STRINGA_Justification, GACT_STRINGLEFT,
					STRINGA_HookType, SHK_CUSTOM,
					End,            
				CHILD_Label, gad[GID_Label5] = LabelObject,
					LABEL_Justification, 0,
					LABEL_Text, "Address:",
					End, 
				LAYOUT_AddChild, gad[GID_Button2] = ButtonObject,
					GA_ID, GID_Button2,
                    GA_Image, img_go,
                    BUTTON_Transparent,  TRUE,
                    BUTTON_BevelStyle,   BVS_NONE,
                    ButtonEnd,
                CHILD_MaxWidth, 20,
				LAYOUT_AddChild, gad[GID_Space_1_1] = SpaceObject,
					GA_ID, GID_Space_1_1,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_UserData, 18,
					SPACE_BevelStyle, 4,
					End,
				CHILD_MaxWidth, 20,
				LAYOUT_AddChild, gad[GID_String4] = StringObject,
					GA_ID, GID_String4,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_TabCycle, TRUE,
					GA_UserData, 20,
					STRINGA_TextVal, "",
					STRINGA_MaxChars, 100,
					STRINGA_Justification, GACT_STRINGLEFT,
					STRINGA_HookType, SHK_CUSTOM,
					End,         
				CHILD_MaxWidth, 150,
				LAYOUT_AddChild, gad[GID_Button5] = ButtonObject,
                    GA_ID, GID_Button5,
                    GA_Image, img_google,
                    BUTTON_BevelStyle,   BVS_NONE,
                    ButtonEnd, 
				CHILD_MaxWidth, 20,
				CHILD_MaxHeight, 20,   
				End,
			EndGroup,
		EndWindow;

	if (!obj[OID_WindowObject1])
		CleanExit("Cannot create obj[OID_WindowObject1]");

	obj[OID_WindowObject2] = WindowObject,
		WA_Left, 98,
		WA_Top, 313,
		WA_Width, 400,
		WA_Height, 300,
		WA_DragBar, TRUE,
		WA_DepthGadget, TRUE,
		WA_CloseGadget, TRUE,
		WA_Activate, TRUE,
		WA_AutoAdjust, TRUE,
		WA_Title, "OWB_GUI - Preferences",
		WA_ScreenTitle, "OWB_GUI - Preferences",
		WA_PubScreen, Screen1,
		WINDOW_GadgetHelp, TRUE,
		WINDOW_IconifyGadget, FALSE,
		WINDOW_IconTitle, "Iconified",
		WINDOW_AppPort, AppPort,
		WINDOW_SharedPort, AppPort,
		WINDOW_HintInfo,Hint_WindowObject2,
		WINDOW_NewMenu, Menu,
		WINDOW_ParentGroup, VGroupObject,
			LAYOUT_SpaceOuter, TRUE,
			LAYOUT_DeferLayout, TRUE,
			LAYOUT_AddChild,  gad[GID_Layout2] = LayoutObject,
				GA_ID, GID_Layout2,
				GA_RelVerify, TRUE,
				GA_GadgetHelp, TRUE,
				GA_UserData, 12,
				LAYOUT_Label, "Look & Feel",
				LAYOUT_Orientation, 1,
				LAYOUT_HorizAlignment, LALIGN_LEFT,
				LAYOUT_VertAlignment, LALIGN_TOP,
				LAYOUT_LabelPlace, BVJ_TOP_LEFT,
				LAYOUT_BevelState, IDS_NORMAL,
				LAYOUT_BevelStyle, 2,
				LAYOUT_FixedVert, FALSE,
				LAYOUT_AddChild, gad[GID_String2] = StringObject,
					GA_ID, GID_String2,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_TabCycle, TRUE,
					GA_UserData, 20,
					STRINGA_TextVal, "",
					STRINGA_MaxChars, 20,
					STRINGA_Justification, GACT_STRINGLEFT,
					STRINGA_HookType, SHK_CUSTOM,
					End,
				CHILD_Label, gad[GID_Label1] = LabelObject,
					LABEL_Justification, 0,
					LABEL_Text, "X Size:",
					End,
				LAYOUT_AddChild, gad[GID_String3] = StringObject,
					GA_ID, GID_String3,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_TabCycle, TRUE,
					GA_UserData, 20,
					STRINGA_TextVal, "",
					STRINGA_MaxChars, 20,
					STRINGA_Justification, GACT_STRINGLEFT,
					STRINGA_HookType, SHK_CUSTOM,
					End,
				CHILD_Label, gad[GID_Label2] = LabelObject,
					LABEL_Justification, 0,
					LABEL_Text, "Y Size:",
					End,
				LAYOUT_AddChild, gad[GID_Chooser1] = ChooserObject,
					GA_ID, GID_Chooser1,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_UserData, 2,
					CHOOSER_Title, "Chooser1",
					CHOOSER_AutoFit, TRUE,
					CHOOSER_PopUp, TRUE,
					CHOOSER_MaxLabels, 10,
					CHOOSER_Offset, 0,
					CHOOSER_Selected, -1,
					CHOOSER_Labels, (ULONG) Ep_Chooser_depth_node,
					End,
				CHILD_Label, gad[GID_Label3] = LabelObject,
					LABEL_Justification, 0,
					LABEL_Text, "Color Depth:",
					End,
				End,
			LAYOUT_AddChild, gad[GID_Layout4] = LayoutObject,
				GA_ID, GID_Layout4,
				GA_RelVerify, TRUE,
				GA_GadgetHelp, TRUE,
				GA_UserData, 12,
				LAYOUT_Label, "Home",
				LAYOUT_Orientation, 1,
				LAYOUT_HorizAlignment, LALIGN_LEFT,
				LAYOUT_VertAlignment, LALIGN_TOP,
				LAYOUT_LabelPlace, BVJ_TOP_LEFT,
				LAYOUT_BevelState, IDS_NORMAL,
				LAYOUT_BevelStyle, 2,
				LAYOUT_FixedVert, FALSE,
				LAYOUT_AddChild, gad[GID_String5] = StringObject,
					GA_ID, GID_String5,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_TabCycle, TRUE,
					GA_UserData, 200,
					STRINGA_TextVal, "",
					STRINGA_MaxChars, 200,
					STRINGA_Justification, GACT_STRINGLEFT,
					STRINGA_HookType, SHK_CUSTOM,
					End,
				CHILD_Label, gad[GID_Label4] = LabelObject,
					LABEL_Justification, 0,
					LABEL_Text, "Home URL:",
					End,
				End,
			LAYOUT_AddChild, gad[GID_Layout3] = LayoutObject,
				GA_ID, GID_Layout3,
				GA_RelVerify, TRUE,
				GA_GadgetHelp, TRUE,
				GA_UserData, 12,
				LAYOUT_Label, "",
				LAYOUT_Orientation, 0,
				LAYOUT_TopSpacing, 50,
				LAYOUT_HorizAlignment, LALIGN_CENTER,
				LAYOUT_VertAlignment, LALIGN_TOP,
				LAYOUT_LabelPlace, BVJ_TOP_CENTER,
				LAYOUT_BevelState, IDS_NORMAL,
				LAYOUT_BevelStyle, 4,
				LAYOUT_FixedHoriz, FALSE,
				LAYOUT_FixedVert, FALSE,
				LAYOUT_AddChild, gad[GID_Button3] = ButtonObject,
					GA_ID, GID_Button3,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_UserData, 0,
					GA_Text, "Save",
					BUTTON_AutoButton, 0,
					BUTTON_BevelStyle, 1,
					BUTTON_Justification, 1,
					End,
				LAYOUT_AddChild, gad[GID_Button4] = ButtonObject,
					GA_ID, GID_Button4,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_UserData, 0,
					GA_Text, "Cancel",
					BUTTON_AutoButton, 0,
					BUTTON_BevelStyle, 1,
					BUTTON_Justification, 1,
					End,
				End,
			EndGroup,
		EndWindow;

	if (!obj[OID_WindowObject2])
		CleanExit("Cannot create obj[OID_WindowObject2]");

	obj[OID_Inforequest1] = RequesterObject,
		REQ_Type,		REQTYPE_INFO,
		REQ_TitleText,		"OWB GUI - Information",
		REQ_BodyText,		"This is just a simple GUI created for the\n"
                            "new browser OWB.\n"
                            "The reason that I created this\n"
                            "is because I wanted something\n"
                            "to run OWB with an easy way.\n\n"
                            "This is version "VERSION"."REVISION" and it is\n"
                            "temporary until OWB get it's own GUI.\n"
                            "Feel free to fix errors and\n"
                            "put new features if you like!\n"
                            "If you do, please send me the source code!\n"
                            "You may contact me at: walkero@yahoo.com",
		REQ_GadgetText,	"Okay",
		TAG_DONE);                             

	if (!obj[OID_Inforequest1])
		CleanExit("Cannot create obj[OID_Inforequest1]");


	obj[OID_WindowObject3] = WindowObject,
		WA_Left, 0,
		WA_Top, 73,
		WA_Width, 170,
		WA_Height, 550,
		WA_SizeGadget, TRUE,
		WA_DragBar, TRUE,
		WA_DepthGadget, TRUE,
		WA_Activate, TRUE,
		WA_AutoAdjust, TRUE,
		WA_Title, "Bookmarks",
		WA_ScreenTitle, PROGNAME " " VERSION"."REVISION " - "DATE" ©"DEVELOPER,
		WA_PubScreen, Screen1,
		WINDOW_GadgetHelp, TRUE,
		WINDOW_IconifyGadget, FALSE,
		WINDOW_IconTitle, "Iconified",
		WINDOW_AppPort, AppPort,
		WINDOW_SharedPort, AppPort,
		WINDOW_HintInfo,Hint_WindowObject3,
		WINDOW_NewMenu, Menu,
		WINDOW_ParentGroup, VGroupObject,
			LAYOUT_SpaceOuter, TRUE,
			LAYOUT_DeferLayout, TRUE,
			LAYOUT_AddChild,  gad[GID_Layout5] = LayoutObject,
				GA_ID, GID_Layout5,
				GA_RelVerify, TRUE,
				GA_GadgetHelp, TRUE,
				GA_UserData, 12,
				LAYOUT_Label, "",
				LAYOUT_Orientation, 1,
				LAYOUT_HorizAlignment, LALIGN_LEFT,
				LAYOUT_VertAlignment, LALIGN_TOP,
				LAYOUT_LabelPlace, BVJ_TOP_CENTER,
				LAYOUT_BevelState, IDS_NORMAL,
				LAYOUT_BevelStyle, 4,
				LAYOUT_AddChild, gad[GID_Layout6] = LayoutObject,
					GA_ID, GID_Layout6,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_UserData, 12,
					LAYOUT_Label, "",
					LAYOUT_Orientation, 0,
					LAYOUT_InnerSpacing, 3,
					LAYOUT_HorizAlignment, LALIGN_LEFT,
					LAYOUT_VertAlignment, LALIGN_TOP,
					LAYOUT_LabelPlace, BVJ_TOP_CENTER,
					LAYOUT_BevelState, IDS_NORMAL,
					LAYOUT_BevelStyle, 4,
					LAYOUT_FixedHoriz, FALSE,
					LAYOUT_FixedVert, FALSE,
                    LAYOUT_AddChild, gad[GID_Button9] = ButtonObject,
                        GA_ID, GID_Button9,
                        GA_Image, img_addr,
                        ButtonEnd,
                    LAYOUT_AddChild, gad[GID_Button10] = ButtonObject,
                        GA_ID, GID_Button10,
                        GA_Image, img_addradd,
                        ButtonEnd,
                    LAYOUT_AddChild, gad[GID_Button11] = ButtonObject,
                        GA_ID, GID_Button11,
                        GA_Image, img_addrdel,
                        ButtonEnd,
					End,             
				LAYOUT_AddChild, gad[GID_Layout7] = LayoutObject,
					GA_ID, GID_Layout7,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_UserData, 12,
					LAYOUT_Label, "",
					LAYOUT_Orientation, 0,
					LAYOUT_HorizAlignment, LALIGN_LEFT,
					LAYOUT_VertAlignment, LALIGN_TOP,
					LAYOUT_LabelPlace, BVJ_TOP_CENTER,
					LAYOUT_BevelState, IDS_NORMAL,
					LAYOUT_BevelStyle, 4,
					LAYOUT_AddChild, gad[GID_Listbrowser1] = ListBrowserObject,
						GA_ID, GID_Listbrowser1,
						GA_RelVerify, TRUE,
						GA_GadgetHelp, TRUE,
						GA_UserData, 13,          
						LISTBROWSER_AutoFit, TRUE,
						LISTBROWSER_ShowSelected, TRUE,
						LISTBROWSER_VerticalProp, TRUE,
						LISTBROWSER_HorizontalProp, TRUE,
						LISTBROWSER_Hierarchical, TRUE,
						End,
					End,
				End,
			EndGroup,
		EndWindow;

	if (!obj[OID_WindowObject3])
		CleanExit("Cannot create obj[OID_WindowObject3]");  


	obj[OID_WindowObject4] = WindowObject,
		WA_Left, 100,
		WA_Top, 250,
		WA_Width, 450,
		WA_Height, 50,
		WA_DragBar, TRUE,
		WA_DepthGadget, TRUE,
		WA_Activate, TRUE,
		WA_CloseGadget, TRUE,
		WA_AutoAdjust, TRUE,
		WA_Title, "Bookmark Edit",
		WA_ScreenTitle, PROGNAME " " VERSION"."REVISION " - "DATE" ©"DEVELOPER,
		WA_PubScreen, Screen1,
		WINDOW_GadgetHelp, TRUE,
		WINDOW_IconifyGadget, FALSE,
		WINDOW_IconTitle, "Iconified",
		WINDOW_AppPort, AppPort,
		WINDOW_SharedPort, AppPort,
		WINDOW_HintInfo,Hint_WindowObject4,
		WINDOW_NewMenu, Menu,
		WINDOW_ParentGroup, VGroupObject,
			LAYOUT_SpaceOuter, TRUE,
			LAYOUT_DeferLayout, TRUE,
			LAYOUT_AddChild,  gad[GID_Layout_4_1] = LayoutObject,
				GA_ID, GID_Layout_4_1,
				GA_RelVerify, TRUE,
				GA_GadgetHelp, TRUE,
				GA_UserData, 12,
				LAYOUT_Label, "",
				LAYOUT_Orientation, 0,
				LAYOUT_HorizAlignment, LALIGN_LEFT,
				LAYOUT_VertAlignment, LALIGN_TOP,
				LAYOUT_LabelPlace, BVJ_TOP_CENTER,
				LAYOUT_BevelState, IDS_NORMAL,
				LAYOUT_BevelStyle, 4,
				LAYOUT_FixedVert, FALSE,
				LAYOUT_AddChild, gad[GID_String_4_1] = StringObject,
					GA_ID, GID_String_4_1,
					GA_RelVerify, TRUE,
					GA_GadgetHelp, TRUE,
					GA_TabCycle, TRUE, 
					STRINGA_TextVal, "",
					STRINGA_MaxChars, 200,
					STRINGA_Justification, GACT_STRINGLEFT,
					STRINGA_HookType, SHK_CUSTOM,
					End,
				CHILD_Label, gad[GID_Label_4_1] = LabelObject,
					LABEL_Justification, 0,
					LABEL_Text, "URL:",
					End,              
                LAYOUT_AddChild, gad[GID_Button_4_1] = ButtonObject,
                    GA_ID, GID_Button_4_1,
					GA_Image, img_edit,
                    BUTTON_BevelStyle,   BVS_NONE,
                    ButtonEnd,
				CHILD_MaxWidth, 30,
				CHILD_MaxHeight, 30,
				End,
			EndGroup,
		EndWindow;

	if (!obj[OID_WindowObject4])
		CleanExit("Cannot create obj[OID_WindowObject4]");

}
void Ep_CloseWindow_Window1(void)
{
	IIntuition->IDoMethod(obj[OID_WindowObject1], WM_CLOSE, NULL);
	win[WID_Window1] = NULL;
}

struct Window *Ep_OpenWindow_Window1(void)
{
	win[WID_Window1] = RA_OpenWindow(obj[OID_WindowObject1]);
	return(win[WID_Window1]);
}

void Ep_CloseWindow_Window2(void)
{
	IIntuition->IDoMethod(obj[OID_WindowObject2], WM_CLOSE, NULL);
	win[WID_Window2] = NULL;
}

struct Window *Ep_OpenWindow_Window2(void)
{
	win[WID_Window2] = RA_OpenWindow(obj[OID_WindowObject2]);
	return(win[WID_Window2]);
}

void Ep_CloseWindow_Window3(void)
{
	IIntuition->IDoMethod(obj[OID_WindowObject3], WM_CLOSE, NULL);
	win[WID_Window3] = NULL;
}

struct Window *Ep_OpenWindow_Window3(void)
{
	win[WID_Window3] = RA_OpenWindow(obj[OID_WindowObject3]);
	return(win[WID_Window3]);
}

void Ep_CloseWindow_Window4(void)
{
	IIntuition->IDoMethod(obj[OID_WindowObject4], WM_CLOSE, NULL);
	win[WID_Window4] = NULL;
}

struct Window *Ep_OpenWindow_Window4(void)
{
	win[WID_Window4] = RA_OpenWindow(obj[OID_WindowObject4]);
	return(win[WID_Window4]);
}

void Ep_CloseScreen_Screen1(void)
{
	if(Screen1)
	{
		IIntuition->UnlockPubScreen(NULL, Screen1);
		Screen1 = NULL;
	}
}

struct Screen *Ep_OpenScreen_Screen1(void)
{
	Screen1 = IIntuition->LockPubScreen(NULL);
	return(Screen1);
}
