/*
**	Handling linked lists 
**	Automatically generated by Emperor
*/

#include "includes.h"

void InitLists()
{
	char *Ep_BrowserListraw[] =
	{
		NULL
	};

	WORD Ep_BrowserListattr[] = { 0 };

	char *Ep_depth_noderaw[] =
	{
 		"32",
		"16",
		NULL
	};

	WORD Ep_depth_nodeattr[] = { 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

	if (!(Ep_Chooser_depth_node = (struct List *) IExec->AllocSysObject(ASOT_LIST,TAG_DONE)))
		CleanExit("Cannot create Ep_Chooser_depth_node list");
	if (!(Ep_Clicktab_depth_node = (struct List *) IExec->AllocSysObject(ASOT_LIST,TAG_DONE)))
		CleanExit("Cannot create Ep_Clicktab_depth_node list");
	if (!(Ep_Listbrowser_depth_node = (struct List *) IExec->AllocSysObject(ASOT_LIST,TAG_DONE)))
		CleanExit("Cannot create Ep_Listbrowser_depth_node list");
	if (!(Ep_Radiobutton_depth_node = (struct List *) IExec->AllocSysObject(ASOT_LIST,TAG_DONE)))
		CleanExit("Cannot create Ep_RadioButton_depth_node list");    
	Ep_AllocNode(Ep_Chooser_depth_node, Ep_depth_noderaw, Ep_depth_nodeattr,LID_CHOOSER);
	Ep_AllocNode(Ep_Clicktab_depth_node, Ep_depth_noderaw, Ep_depth_nodeattr,LID_CKTAB);
	Ep_AllocNode(Ep_Listbrowser_depth_node, Ep_depth_noderaw, Ep_depth_nodeattr,LID_LBROWSE);     
	Ep_AllocNode(Ep_Radiobutton_depth_node, Ep_depth_noderaw, Ep_depth_nodeattr,LID_RBUTTON);

	if (!(Ep_Chooser_BrowserList = (struct List *) IExec->AllocSysObject(ASOT_LIST,TAG_DONE)))
		CleanExit("Cannot create Ep_Chooser_BrowserList list");
	if (!(Ep_Clicktab_BrowserList = (struct List *) IExec->AllocSysObject(ASOT_LIST,TAG_DONE)))
		CleanExit("Cannot create Ep_Clicktab_BrowserList list");
	if (!(Ep_Listbrowser_BrowserList = (struct List *) IExec->AllocSysObject(ASOT_LIST,TAG_DONE)))
		CleanExit("Cannot create Ep_Listbrowser_BrowserList list");
	if (!(Ep_Radiobutton_BrowserList = (struct List *) IExec->AllocSysObject(ASOT_LIST,TAG_DONE)))
		CleanExit("Cannot create Ep_RadioButton_BrowserList list");  
	Ep_AllocNode(Ep_Chooser_BrowserList, Ep_BrowserListraw, Ep_BrowserListattr,LID_CHOOSER);
	Ep_AllocNode(Ep_Clicktab_BrowserList, Ep_BrowserListraw, Ep_BrowserListattr,LID_CKTAB);
	Ep_AllocNode(Ep_Listbrowser_BrowserList, Ep_BrowserListraw, Ep_BrowserListattr,LID_LBROWSE);
	Ep_AllocNode(Ep_Radiobutton_BrowserList, Ep_BrowserListraw, Ep_BrowserListattr,LID_RBUTTON);
	
	//if (!(bkmlist = (struct List *) IExec->AllocSysObject(ASOT_LIST,TAG_DONE)))
	//	  CleanExit("Cannot create bkmlist list");
	//Ep_AllocNode(bkmlist, Ep_bkmlistraw, Ep_bkmlistattr,LID_LBROWSE);
	
}

void Ep_AllocNode(struct List *Ep_List, char **Ep_Labels, WORD *Ep_Attributes,UBYTE kind)
{
	WORD Ep_Counter1 = 0,Ep_Counter2 = 0;
	struct Node *Ep_Node;

	IExec->NewList(Ep_List);
	while(*Ep_Labels)
	{
		switch(kind)
		{
			case LID_CHOOSER:
				{
					Ep_Node = IChooser->AllocChooserNode(CNA_Text, *Ep_Labels,
								CNA_Disabled, Ep_Attributes[Ep_Counter1],
 								CNA_ReadOnly, Ep_Attributes[Ep_Counter1 + 1],
								TAG_DONE);
					if(Ep_Node)	IExec->AddTail(Ep_List, Ep_Node);
					Ep_Labels++;
					Ep_Counter1 += 12;
				}
				break;
			case LID_CKTAB:
				{
					Ep_Node = IClickTab->AllocClickTabNode(TNA_Text, *Ep_Labels,
								TNA_Disabled, Ep_Attributes[Ep_Counter1],
								TNA_Number, Ep_Counter2,
								TAG_DONE);
					if(Ep_Node)	IExec->AddTail(Ep_List, Ep_Node);
					Ep_Labels++;
					Ep_Counter1 += 12;
					Ep_Counter2++;
				}
				break;
			case LID_LBROWSE:
				{
					Ep_Counter2 = 0;
					if(Ep_Attributes[Ep_Counter1 + 1]) Ep_Counter2 += 1;
					if(Ep_Attributes[Ep_Counter1 + 2]) Ep_Counter2 += 4;
					if(Ep_Attributes[Ep_Counter1 + 3]) Ep_Counter2 += 8;
					if(Ep_Attributes[Ep_Counter1 + 4]) Ep_Counter2 += 16;
					Ep_Node = IListBrowser->AllocListBrowserNode(1, LBNCA_Text, *Ep_Labels,
								LBNCA_CopyText, TRUE,
								LBNA_Generation, Ep_Attributes[Ep_Counter1 + 10],
								LBNA_Column, Ep_Attributes[Ep_Counter1 + 11],
								LBNA_Flags, Ep_Counter2,
								LBNA_Selected, Ep_Attributes[Ep_Counter1 + 5],
								LBNA_CheckBox, Ep_Attributes[Ep_Counter1 + 6],
								LBNA_Checked, Ep_Attributes[Ep_Counter1 + 7],
								TAG_DONE);
					if(Ep_Node)	IExec->AddTail(Ep_List, Ep_Node);
					Ep_Labels++;
					Ep_Counter1 += 12;
				}
				break;
			case LID_RBUTTON:
				{
					Ep_Node = IRadioButton->AllocRadioButtonNode(1, RBNA_Labels, *Ep_Labels,
								TAG_DONE);
					if(Ep_Node)	IExec->AddTail(Ep_List, Ep_Node);
					Ep_Labels++;
				}
				break;
		};
	}
}



void CleanupLists()
{
	if (Ep_Chooser_depth_node)
	{
		FreeCommonList(Ep_Chooser_depth_node,LID_CHOOSER);
		IExec->FreeSysObject(ASOT_LIST,Ep_Chooser_depth_node);
	}
	if (Ep_Clicktab_depth_node)
	{
		FreeCommonList(Ep_Clicktab_depth_node,LID_CKTAB);
		IExec->FreeSysObject(ASOT_LIST,Ep_Clicktab_depth_node);
	}
	if (Ep_Listbrowser_depth_node)
	{
		FreeCommonList(Ep_Listbrowser_depth_node,LID_LBROWSE);
		IExec->FreeSysObject(ASOT_LIST,Ep_Listbrowser_depth_node);
	}
	if (Ep_Radiobutton_depth_node)
	{
		FreeCommonList(Ep_Radiobutton_depth_node,LID_RBUTTON);
		IExec->FreeSysObject(ASOT_LIST,Ep_Radiobutton_depth_node);
	}
	if (Ep_Chooser_BrowserList)
	{
		FreeCommonList(Ep_Chooser_BrowserList,LID_CHOOSER);
		IExec->FreeSysObject(ASOT_LIST,Ep_Chooser_BrowserList);
	}
	if (Ep_Clicktab_BrowserList)
	{
		FreeCommonList(Ep_Clicktab_BrowserList,LID_CKTAB);
		IExec->FreeSysObject(ASOT_LIST,Ep_Clicktab_BrowserList);
	}
	if (Ep_Listbrowser_BrowserList)
	{
		FreeCommonList(Ep_Listbrowser_BrowserList,LID_LBROWSE);
		IExec->FreeSysObject(ASOT_LIST,Ep_Listbrowser_BrowserList);
	}
	if (Ep_Radiobutton_BrowserList)
	{
		FreeCommonList(Ep_Radiobutton_BrowserList,LID_RBUTTON);
		IExec->FreeSysObject(ASOT_LIST,Ep_Radiobutton_BrowserList);
	}
}

void FreeCommonList(struct List *list, UBYTE kind)
{
	struct Node 	*node,*nextnode;

	node = list->lh_Head;
	while((nextnode = node->ln_Succ))
	{
		switch(kind)
		{
			case LID_CHOOSER:
				IChooser->FreeChooserNode(node);
				break;
			case LID_CKTAB:
				IClickTab->FreeClickTabNode(node);
				break;
			case LID_LBROWSE:
				IListBrowser->FreeListBrowserNode(node);
				break;
			case LID_RBUTTON:
				IRadioButton->FreeRadioButtonNode(node);
				break;
			case LID_SPBAR:
				ISpeedBar->FreeSpeedButtonNode(node);
				break;
		}
		node = nextnode;
	}
	IExec->NewList(list);           
}

